sudo: required
services: 
    - docker

before_install:
    - docker pull nellev/rbio
    - docker run -d -p 127.0.0.1:80:4567 nellev/rbio /bin/sh -c "cd ~; "
    - docker ps -a


script:
    - docker run -ti -v $(pwd):/home/rstudio/repo -w /home/rstudio/repo nellev/rbio /bin/bash -e ".build_tools/travis/test_script.sh"


deploy:
    provider: pages
    skip-cleanup: true
    # Set in the settings page of your repository, as a secure variable
    github-token: $GH_TOKEN  
    keep-history: true
    local-dir: doc/reports
    on:
        branch: master

